### ISSUE TITLE
Error while updating SWRLTab plugin to version 1.0.0-beta-51

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/swrltab-plugin#29]
```
Downloading the SWRLTab plugin (Version 1.0.0.beta-51) 
Downloading the SWRLTab plugin from: https://github.com/protegeproject/swrltab-plugin/releases/download/releases-1.0.0-beta-51/swrltab-plugin-1.0.0-beta-51.jar 
An error occurred whilst downloading and installing the SWRLTab plugin: https://github.com/protegeproject/swrltab-plugin/releases/download/releases-1.0.0-beta-51/swrltab-plugin-1.0.0-beta-51.jar 
java.io.FileNotFoundException: https://github.com/protegeproject/swrltab-plugin/releases/download/releases-1.0.0-beta-51/swrltab-plugin-1.0.0-beta-51.jar
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835) ~[na:1.8.0_40]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[na:1.8.0_40]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[na:1.8.0_40]
	at org.protege.editor.core.update.PluginInstaller.downloadPlugin(PluginInstaller.java:128) [protege-editor-core.jar:na]
	at org.protege.editor.core.update.PluginInstaller.install(PluginInstaller.java:93) [protege-editor-core.jar:na]
	at org.protege.editor.core.update.PluginInstaller.lambda$run$31(PluginInstaller.java:57) [protege-editor-core.jar:na]
	at org.protege.editor.core.update.PluginInstaller$$Lambda$90/1530712989.run(Unknown Source) [protege-editor-core.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
```

**Comment by martinjoconnor** [comment]
Fixed. Thanks for spotting this. Was experimenting with a new release script.
